# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#rake secret to create new key to replace
development:
  secret_key_base: 7454b28a39e95ef29630cd582517ef3c55e5850aa1c8d6c61fc4943f0898662a72f0f48d2f688301ffef1881ac7215213f7f7ab434d7dc87eef1a16b13112bdc

test:
  secret_key_base: cb7ec8c2e6ab70afa29f12b1923f009a735bf245bf0880ca1724f913f98ee88d855011bec5a3f5606da084d0ffd0d38c9ad899b7ced74362d5e24e94edc3ccc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
